version: 1.0
ansys_em_root: "C:\\Program Files\\ANSYS Inc\\v261\\AnsysEM"
host: "127.0.0.1"
port: 50065
enable_io_manager: true
debug: true

visit_types:
  Database: true
  MaterialDef: true
  PadstackDef: true
  PadstackDefData: true
  ComponentDef: true
  ComponentModel: true
  Cell: true
  Layout: true
  Rectangle: true
  Circle: true
  Polygon: true
  Path: true
  PadstackInstance: true
  ComponentGroup: true
  Structure3D: true
  ViaGroup: true

match_rules:
  MaterialDef: [MatchByName]
  PackageDef: [MatchByName]
  ComponentDef: [MatchByName]
  PadstackDef: [MatchByName]
  Cell: [MatchByName]
  Rectangle: [MatchByLayerName, MatchByRectangleProperties]
  Circle: [MatchByLayerName, MatchByCircleProperties]
  Polygon: [MatchByLayerName, MatchByPolygonProperties]
  Path: [MatchByLayerName, MatchByPathProperties]
  PadstackInstance: [MatchByPadstackInstanceProperties]
  ComponentGroup: [MatchByName]
