version: 1.0
ansys_em_root: "C:\\Program Files\\ANSYS Inc\\v261\\AnsysEM"
host: "127.0.0.1"
port: 50065
enable_io_manager: true
debug: true

visit_rules:
  Database:
    - directory
    - version
    - source
    - source_version
    - material_defs
    - padstack_defs
    - component_defs
    - apd_bondwire_defs
    - jedec4_bondwire_defs
    - jedec5_bondwire_defs
    - package_defs
    - circuit_cells
    # - footprint_cells
  MaterialDef:
    - definition_type
    - name
    - material_properties
  PadstackDef:
    - definition_type
    - name
    - data
  PadstackDefData:
    - material
    - layer_names
    - pad_parameters
  ComponentDef:
    - definition_type
    - name
    # - footprint
    - component_models
    # - component_pins
  ComponentModel:
    - reference_file
    - name
    - component_model_type
  BondwireDef:
    - definition_type
    - name
    - parameters
    - bondwire_type
  PackageDef:
    - definition_type
    - name
    - exterior_boundary
    - height
    - operating_power
    - maximum_power
    - thermal_conductivity
    - theta_jb
    - theta_jc
    - heat_sink
  Cell:
    - layout
    - is_footprint
    - is_blackbox
    - suppress_pads
    - anti_pads_always_on
    - anti_pads_option
    - is_symbolic_footprint
    - name
    - design_mode
  Layout:
    - primitives
    - padstack_instances
    - groups
  Primitive:
    - net_name
    - primitive_type
    - layer_name
    - is_negative
    - is_void
    - has_voids
    - owner
    - is_parameterized
    - is_zone_primitive
    # - can_be_zone_primitive
    - voids
  Rectangle:
    - parameters
  Circle:
    - parameters
  Polygon:
    - polygon_data
  PolygonData:
    - points
    - is_closed
    - sense
  Path:
    - center_line
    - width
  PrimitiveInstanceCollection:
    - geometry
    - positions
    - instantiated_geometry
  Bondwire:
   - material
   - type
   - cross_section_type
   - cross_section_height
   - definition_name
   - trajectory
   - width
   - start_elevation
   - end_elevation
  HierarchyObj:
    - net_name
    - transform
    - name
    - component_def
    - placement_layer
    - location
    - solve_independent_preference
  Transform:
    - scale
    - rotation
    - offset_x
    - offset_y
    - mirror
  ComponentGroup:
    - num_pins
    - component_property
    - component_type
  ComponentProperty:
    - package_mounting_offset
    - package_def
    # - model
  Structure3D:
    - material
    - thickness
    - mesh_closure
  ViaGroup:
    - outline
    - conductor_percentage
    - persistent

match_rules:
  MaterialDef: [MatchByName]
  PackageDef: [MatchByName]
  ComponentDef: [MatchByName]
  PadstackDef: [MatchByName]
  ApdBondwireDef: [MatchByName]
  Cell: [MatchByName]
  Rectangle: [MatchByLayerName, MatchByRectangleProperties]
  Circle: [MatchByLayerName, MatchByCircleProperties]
  Polygon: [MatchByLayerName, MatchByPolygonProperties]
  Path: [MatchByLayerName, MatchByPathProperties]
  PadstackInstance: [MatchByPadstackInstanceProperties]
  ComponentGroup: [MatchByName]

filter_rules:
  ObjBase:
    excluded_properties:
      - id
      - owner
    reserved_properties:
      - id
      - name
